import "../styles/main.css";
import { Poppins, PlayfairDisplay } from "@/utils/font";

export const metadata = {
  title: "Kandinsky",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Poppins.variable} ${PlayfairDisplay.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
